language: python
cache: pip
python:
- '3.4'
- '3.5'
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
script: cd tests && python -m tests
after_success: cd ..
deploy:
  provider: pypi
  user: harens
  password:
    secure: A7Fa0QRs9z/N/FmyQ5lvaLskyLUcZevz/bNF2mHK8alotcjLx9jPQVWJ0CaoECTb7Sck1ur3BnqxbxnfzI7lxu60I1CPptXMHJnzdw0Znujk076u5Q6H8l+flgYAGvGYt1r2A4ZSdTa/RziTk6DamZ3VyPYRvOYN8SzFT0MYC3I/lh82AJps9Khp4LGCYmeYomWkzocIr/NFGsO9aOT3rgk9EEHmZv/6tdGYiI0Km/J+8MuYmA7gQF0qDKJ/78wO3yw0vYT6B5/zPF3fMloHFwglZeCeoaGh/CWR4RzokM2ZUBGdmkUi2pEfpaiR0wHToRMPLKHUwHW4yLDf6slkPgb86VSmkn8hh64Mp0+QqUARx1y2k/87ZcQWabjppAzISSt6S48kW2qCW5CqUlhOTunDKivgNTpTAWUuQHaLMOIFdgQFZ8o1fSE5etWNTVLMasYR9HMhcdiTNvDerviNUI58LZp5MuLcfOLWuncnojgo+/fJJGn5OI1rW0fU3prwksQEfIHe833pwtzK21mUAo1LJNMsxZLuQz1C4kqrrBi0/11+zpen9eUvL2IaT/2p1d/o4pM82ErVIBhM/S0ism5DcUSTMkdOJcph1poFPh4mLipViiYrGd+O2MMfXx5eGE7ijpu1xdiioyTWHyIUrpg7zoFgKbkNk//IbPVccSk=
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always